#!/usr/bin/env node
// Codegen: bundles every `prompts/*.md` into a typed Record<string, string>
// at `apps/web/src/lib/agent/prompts.generated.ts`. Run before dev/build/test.
//
// Why this exists: `system-prompt.ts` previously read `.md` files via
// `readFileSync(import.meta.url + "/prompts")`. Vercel's nft bundler can't
// trace a path computed from `import.meta.url`, so the prompts directory
// wasn't included in the `/api/agent` serverless function and prod 500'd
// with ENOENT. Static imports are the only bundler-agnostic fix.

import { readFileSync, readdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const HERE = dirname(fileURLToPath(import.meta.url))
const PROMPTS_DIR = join(HERE, "..", "src", "lib", "agent", "prompts")
const OUT_PATH = join(HERE, "..", "src", "lib", "agent", "prompts.generated.ts")

const files = readdirSync(PROMPTS_DIR)
  .filter((f) => f.endsWith(".md"))
  .sort()

const entries = files.map((file) => {
  const key = file.replace(/\.md$/, "")
  const text = readFileSync(join(PROMPTS_DIR, file), "utf-8").trimEnd()
  return [key, text]
})

const body = entries
  .map(([key, text]) => `  ${JSON.stringify(key)}: ${JSON.stringify(text)},`)
  .join("\n")

const out = `// AUTO-GENERATED by apps/web/scripts/build-prompts.mjs. Do not edit.
// Source: apps/web/src/lib/agent/prompts/*.md
// Regenerate: pnpm --filter @festivus/web build:prompts

export const PROMPT_TEXT: Record<string, string> = {
${body}
}
`

writeFileSync(OUT_PATH, out)
console.error(`build-prompts: wrote ${entries.length} prompts to ${OUT_PATH}`)
