/**
 * Spec 029: per-table list of agent-editable field names.
 *
 * This mirrors the allowlist encoded in
 * `api/src/validation/patch-schemas.ts`. A parity test in
 * `allowlist.test.ts` extracts field names from that server-side
 * module and asserts this mirror stays in sync. Do not edit this file
 * without updating patch-schemas.ts (or vice versa) — the drift test
 * will fail.
 *
 * Source of truth (for review): `docs/exec-plans/active/029-field-allowlist.md`.
 */

export const AGENT_EDITABLE_TABLES = [
  "robots",
  "policies",
  "datasets",
  "benchmarks",
  "deploy_notes",
  "environments",
  "tasks",
  "papers",
  "hardware",
  "compatibility_edges",
  "laundry_compat_edges",
] as const

export type IAgentEditableTable = (typeof AGENT_EDITABLE_TABLES)[number]

export const AGENT_EDITABLE_FIELDS: Record<IAgentEditableTable, readonly string[]> = {
  robots: [
    "manufacturer",
    "type",
    "dof",
    "actuators",
    "price_usd",
    "weight_kg",
    "deploy_readiness",
    "image_url",
    "community_size",
    "description",
    "product_page_url",
    "category",
    "form_factor",
    "price_availability",
  ],
  policies: [
    "author",
    "framework",
    "license",
    "task_description",
    "skill_type",
    "paper_arxiv_url",
    "evidence_level",
  ],
  datasets: ["description", "episodes", "robots", "source", "format"],
  benchmarks: [
    "description",
    "task_scope",
    "metric",
    "source_url",
    "environment",
    "difficulty",
  ],
  deploy_notes: ["robot_type", "severity", "description"],
  environments: [
    "kind",
    "simulator",
    "scene",
    "description",
    "deploy_command",
    "preview_description",
  ],
  tasks: ["category", "description", "difficulty", "has_real_world_demo"],
  papers: ["venue", "date", "arxiv_url", "citations", "abstract"],
  hardware: ["kind", "manufacturer", "description"],
  compatibility_edges: [
    "status",
    "success_rate",
    "episodes_tested",
    "environment",
    "source",
    "evidence_url",
  ],
  laundry_compat_edges: [
    "tier",
    "status",
    "environment",
    "simulator_first",
    "evidence_type",
    "evidence_url",
    "confidence",
    "notes",
  ],
}
